plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console:  "off"
  import/extensions: "off" 

